apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/yherzog-tenant/devfile-sample-python-basic/devfile-sample-python-basic@sha256:3202ef186e41d92ed9423cc625001b90721e1668620c3dca4a7bf084c4921326
        name: my-python
        resources: {}
status: {}
