apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/yherzog-tenant/devfile-sample-python-basic/devfile-sample-python-basic@sha256:12d18dcd8fc05cd0829bd584325f0ba69cb18f4d64f57645538a48578fd7ba59
        name: my-python
        resources: {}
status: {}
